log_level: debug
time_zone: Asia/Tokyo
healthcheck:
  host: 0.0.0.0
  port: 8080
tasks:
  test:
    env:
      hoge: fuga
    command: echo
    retry_type: fixed
    use_template: true
    args:
      - '{{time "2006-01-02T15:04:05Z07:00"}} {{env "hoge"}} {{count}}'
    schedule:
      "* * * * *"
