name: Test and Publish Docker

on:
  push:
    branches:
      - master

jobs:
  test_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: chronos
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Cache Go modules
        id: cache-go
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download Go modules
        shell: bash
        if: ${{ steps.cache-go.outputs.cache-hit != 'true' }}
        run: go mod download
      - name: Go build
        shell: bash
        run: go build ./...
      - name: Go test
        shell: bash
        run: go test
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker-build
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
